
## Live BASE URL http://165.22.80.212:8000
## http://154.118.38.171:8000/api/user-agent/login

# Get me the list a valid alert types
GET http://165.22.80.212:8000/api/enums

###
# Get list of registered users
GET http://165.22.80.212:8000/api/user
Content-Type: application/json

###
# Agent Login
POST http://165.22.80.212:8000/api/user-agent/login
Content-Type: application/json

{
	"phoneNumber":"09037737658",
	"password":"password"
}
### 
# Create user
POST http://165.22.80.212:8000/api/user
Content-Type: application/json
state: taraba

{
    "user" : {
		"fullName": "Tester",
		"phoneNumber": "09010000001",
		"gender": "male",
		"address": "Some address",
        "userType": "citizen"
	}
}

###
# Login user
POST http://165.22.80.212:8000/api/user/login
Content-Type: application/json
state: nasarawa

{
    "phoneNumber" : "09037737658"
}


###
# Create an alert
POST  http://165.22.80.212:8000/api/alert
Content-Type: application/json
state: nasarawa

{
	"alert":{
		"userId":"5ebac98660d179001c3467f1",
		"alertType":"fire",
		"location":"6.4623144,3.4778092",
		"priority": "medium",
		"state": "taraba",
		"comment": "testing2",
		"pictures": ["picture1.png", "picture2.png"],
		"videos": ["video1.png", "video2.png"],
		"audios": [""]
	}
}

###
# Create Feedback
POST  http://165.22.80.212:8000/api/feedback
Content-Type: application/json
state: nasarawa

{
	"userId":null,
	"comment":"fire",
	"feedback":"REST test"
}
# {comment: Httpexception feedback , feedback: issues, userId: anonymous}

###
# Get lsit of alerts via user ID
GET http://165.22.80.212:8000/api/alert
Content-Type: application/json


###
# Get LGA's
GET http://165.22.80.212:8000/api/lgas



###
# Get Ward/Communities
GET http://165.22.80.212:8000/api/ward